export const formsText = {
  emailLabel: 'Email',
  passwordLabel: 'Password',
  confirmPasswordLabel: 'Confirm Password',
  emailPlaceholder: 'Email',
  passwordPlaceholder: '******************',
  signInButton: 'Sign In',
  registerButton: 'Register',
  titleLabel: 'Title',
  descriptionLabel: 'Description',
  dateLabel: 'Date',
  categoryLabel: 'Category',
  imageLabel: 'Image URL',
  titlePlaceholder: 'Title',
  descriptionPlaceholder: 'Description',
  datePlaceholder: 'Date',
  categoryPlaceholder: 'Category',
  imagePlaceholder: 'Image URL',
  createEventButton: 'Create Event',
};
